mall/urls.py
from django.urls import path
from . import views

urlpatterns = [ # IP주소/mall/
    path('',views.ItemList.as_view()),
    path('<int:pk>/', views.ItemDetail.as_view()),     # item 관련 pk
    path('<int:pk>/new_comment/', views.new_comment),
    path('update_comment/<int:pk>/', views.CommentUpdate.as_view()),              # comment 관련 pk
    path('delete_comment/<int:pk>/', views.delete_comment),
    path('create_item/', views.ItemCreate.as_view()),
    path('update_item/<int:pk>/', views.ItemUpdate.as_view()),
    path('category/<str:slug>/', views.category_page),         # 괄호 안에 첫 번째가 url이고 두번째가 처리할 함수 호출 # IP주소/blog/category/slug
    path('tag/<str:slug>/', views.tag_page),     # IP주소/blog/tag/slug
    path('manufacturer/<int:pk>/', views.manufacturer_page),
    path('search/<str:q>/',views.ItemSearch.as_view()),
    path('my_page/', views.my_page),  #마이페이지에 대한 내용.
    path('add_cart/<int:pk>/', views.add_cart),
    path('remove/<int:pk>/', views.cart_remove),
    path('full_remove/<int:pk>/', views.full_remove),

    #path('cart_detail/', views.cart_detail),

    #path('', views.index),  # IP주소/blog
    #path('<int:pk>/', views.single_post_page)
]

myDjangoPrj2/myDjangoPrj2/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

myDjangoPrj2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from mall import views
from single_pages import views

urlpatterns = [
    path('admin/', admin.site.urls),     # IP 주소/admin
    path('mall/', include('mall.urls')), # IP 주소/mall
    path('', include('single_pages.urls')), # IP 주소/
    path('accounts/', include('allauth.urls')),
    path('markdownx/', include('markdownx.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mall/models.py
from django.db import models
from django.contrib.auth.models import User
from markdownx.models import MarkdownxField
from markdownx.utils import markdown
import os
import uuid

# Create your models here.

class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)   # BEST, 시즌 한정, 한정 재고
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):  # IP주소/mall/tag/slug
        return f'/mall/tag/{self.slug}/'

class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)  # 밀크, 다크, 화이트
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):                             # 카테고리부분
        return f'/mall/category/{self.slug}'

    class Meta:                                               # 카테고리부분
        verbose_name_plural = 'Categories'

class Manufacturer(models.Model):
    name = models.CharField(max_length=30)              # 허쉬, 기라델리...
    CEO = models.CharField(max_length=20)
    address = models.CharField(max_length=80)
    contact_number = models.CharField(max_length=20)
    logo_image = models.ImageField(upload_to='mall/images/', blank=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/mall/manufacturer/{self.pk}/'

class Item(models.Model):
    name = models.CharField(max_length=30)
    hook_text = models.CharField(max_length=100, blank=True)
    description = MarkdownxField()
    image = models.ImageField(upload_to='item/item_images/%Y/%m/%d/', blank=True)
    price = models.PositiveIntegerField()
    manufacturer = models.ForeignKey(Manufacturer, null=True, blank=True, on_delete=models.SET_NULL)
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)
    tags = models.ManyToManyField(Tag, blank=True)
    countryOfOrigin = models.CharField(max_length=30)

    def __str__(self):
        return f'[{self.pk}] {self.name} - {self.price}'

    def get_absolute_url(self):
        return f'/mall/{self.pk}/'

    def get_avatar_url(self):
        if self.author.socialaccount_set.exists():
            return self.author.socialaccount_set.first().get_avatar_url()
        else:
            return 'https://dummyimage.com/50x50/ced4da/6c757d.jpg'

    def get_description_markdown(self):
        return markdown(self.description)

class Comment(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)  # 왜 다대일 관계인지 다시 생각해보기.
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.author} : {self.content}'

    def get_absolute_url(self):
        return f'{self.item.get_absolute_url()}#comment-{self.pk}'

    def get_avatar_url(self):
        if self.author.socialaccount_set.exists():
            return self.author.socialaccount_set.first().get_avatar_url()
        else:
            return 'https://dummyimage.com/50x50/ced4da/6c757d.jpg'

class Cart(models.Model):
    cart_id= models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        ordering = ['date_added']

    def __str__(self):
        return str(self.cart_id)

class CartItem(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    def sub_total(self):
        return self.item.price * self.quantity

    def __str__(self):
        return str(self.item)

mall/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)  # 나머지는 다 자동으로 가져와 짐.

mall/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from .models import Item, Category, Tag, Manufacturer, Comment, Cart, CartItem
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.utils.text import slugify
from .forms import CommentForm
from django.shortcuts import get_object_or_404
from django.db.models import Q
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.

class ItemList(ListView):
    model = Item
    ordering = 'pk'
    paginate_by = 6 # 페이지네이션

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ItemList, self).get_context_data()
        context['categories'] = Category.objects.all()                                   # 카테고리부분
        context['no_category_item_count'] = Item.objects.filter(category=None).count
        context['manufacturers'] = Manufacturer.objects.all()
        return context

class ItemSearch(ItemList): # ListView 상속, item_list, item_list.html
    paginate_by = None

    def get_queryset(self):
        q = self.kwargs['q']
        item_list = Item.objects.filter(
            Q(name__contains=q)
        ).distinct()
        return item_list

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ItemSearch, self).get_context_data()
        q = self.kwargs['q']
        context['search_info'] = f'Search : {q} ({self.get_queryset().count()})'
        return context


class ItemDetail(DetailView):
    model = Item

    def get_context_data(self, **kwargs):     # 카테고리부분
        context = super(ItemDetail, self).get_context_data()    # 슈퍼 해당되는 내용 ItemDetail임을 명심하자
        context['categories'] = Category.objects.all()
        context['no_category_item_count'] = Item.objects.filter(category=None).count
        context['manufacturers'] = Manufacturer.objects.all()
        context['comment_form'] = CommentForm
        return context

def category_page(request, slug):
    if slug == 'no_category':
        category = '미분류'
        item_list = Item.objects.filter(category=None)                     # 카테고리부분
    else:
        category = Category.objects.get(slug=slug)
        item_list = Item.objects.filter(category=category)
    return render(request, 'mall/item_list.html', {
        'category' : category,                                        # 템플릿이 사용하는 변수는 따옴표 안에 있음 :은 =과 같은 역할
        'item_list' : item_list,
        'categories' : Category.objects.all(),
        'no_category_item_count' : Item.objects.filter(category=None).count,
        'manufacturers' : Manufacturer.objects.all()
    })


def tag_page(request, slug):
    tag = Tag.objects.get(slug=slug)
    item_list = tag.item_set.all()
    return render(request, 'mall/item_list.html', {
        'tag' : tag,
        'item_list': item_list,
        'categories': Category.objects.all(),
        'no_category_item_count': Item.objects.filter(category=None).count,
        'manufacturers': Manufacturer.objects.all()
    })

def manufacturer_page(request, pk): #, slug):
    manufacturer = Manufacturer.objects.get(pk=pk)
    item_list = Item.objects.filter(manufacturer=manufacturer)
    return render(request, 'mall/item_list.html', {
        'manufacturer': manufacturer,  # 템플릿이 사용하는 변수는 따옴표 안에 있음 :은 =과 같은 역할
        'item_list': item_list,
        'manufacturers': Manufacturer.objects.all(),
        'categories': Category.objects.all(),
        'no_category_item_count': Item.objects.filter(category=None).count,
    })

def my_page(request, total=0, counter=0, cart_items =None):
    comment_list = Comment.objects.filter(author=request.user)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.item.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request, 'mall/my_page.html', {
        'manufacturers': Manufacturer.objects.all(),
        'categories': Category.objects.all(),
        'no_category_item_count': Item.objects.filter(category=None).count,
        'comment_list': comment_list,
        'cart_items': cart_items,
        'total': total,
        'counter': counter,
    })

def new_comment(request, pk):
    if request.user.is_authenticated:
        item = get_object_or_404(Item, pk=pk)
        if request.method == 'POST':
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.item = item
                comment.author = request.user
                comment.save()
                return redirect(comment.get_absolute_url())
        else: # GET
            return redirect(item.get_absolute_url())
    else:
        raise PermissionDenied

class CommentUpdate(LoginRequiredMixin, UpdateView):
    model = Comment
    form_class = CommentForm
    # CreateView, UpdateView, form을 사용하면
    # 템플릿 모델명_form : comment_form

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(CommentUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CommentUpdate, self).get_context_data()
        context['categories'] = Category.objects.all()                                   # 카테고리부분 사이드바 내용 위해 추가해줌.
        context['no_category_item_count'] = Item.objects.filter(category=None).count
        context['manufacturers'] = Manufacturer.objects.all()
        return context


def delete_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    item = comment.item
    if request.user.is_authenticated and request.user == comment.author:
        comment.delete()
        return redirect(item.get_absolute_url())
    else:
        PermissionDenied


class ItemUpdate(LoginRequiredMixin, UpdateView):
    model = Item
    fields = ['name','hook_text', 'description', 'image','price', 'manufacturer','category','countryOfOrigin']  # , 'tags'
    # 템플릿 item_form

    template_name = 'mall/item_update_form.html' # 클래스에서도 직접적으로 템플릿을 부를 수 있다.

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and (request.user.is_superuser or request.user.is_staff):
            return super(ItemUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

    def form_valid(self, form):
        response = super(ItemUpdate, self).form_valid(form)
        self.object.tags.clear()
        tags_str = self.request.POST.get('tags_str')
        if tags_str:
            tags_str = tags_str.strip()
            tags_str = tags_str.replace(',', ';')
            tags_list = tags_str.split(';')
            for t in tags_list:
                t = t.strip()
                tag, is_tag_created = Tag.objects.get_or_create(name=t)  # 태그 기존에 있는 거 가져오든지 아님 새로 만드는 행동함.
                if is_tag_created:
                    tag.slug = slugify(t, allow_unicode=True)  # 슬러그까지 추가해서 저장.
                    tag.save()
                self.object.tags.add(tag)
        return response

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ItemUpdate, self).get_context_data()
        if self.object.tags.exists():
            tags_str_list = list()                # string 배열들로 만들고 하나의 string으로 만듦.
            for t in self.object.tags.all():
                tags_str_list.append(t.name)
            context['tags_str_default'] = ';'.join(tags_str_list)      # 다 합쳐서 각각을 ;으로 구분하게 만듦.
        context['categories'] = Category.objects.all()                                   # 카테고리부분 사이드바 내용 위해 추가해줌.
        context['no_category_item_count'] = Item.objects.filter(category=None).count
        context['manufacturers'] = Manufacturer.objects.all()
        return context

class ItemCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Item
    fields = ['name', 'hook_text', 'description', 'image', 'price', 'manufacturer', 'category', 'countryOfOrigin'] # , 'tags' 태그 구분 딜리미터 , ; 만 씀.
    # 템플릿 item_form
    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated and (current_user.is_superuser or current_user.is_staff):
            form.instance.author = current_user
            response = super(ItemCreate, self).form_valid(form)
            tags_str = self.request.POST.get('tags_str') # POST 우리가 쓰고 있는 모델명이 아니라 사용자가 request할 떄 URL없이 비교적 긴 데이터 전달할 때 쓰는 전달 방식
            if tags_str :
                tags_str = tags_str.strip()
                tags_str = tags_str.replace(',',';')
                tags_list = tags_str.split(';')
                for t in tags_list:
                    t = t.strip()
                    tag, is_tag_created = Tag.objects.get_or_create(name=t)       # 태그 기존에 있는 거 가져오든지 아님 새로 만드는 행동함.
                    if is_tag_created:
                        tag.slug = slugify(t, allow_unicode = True)               # 슬러그까지 추가해서 저장.
                        tag.save()
                    self.object.tags.add(tag)
            return response
        else:
            return redirect('/mall/')

    # 템플릿 : 모델명_form.html
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ItemCreate, self).get_context_data()
        context['categories'] = Category.objects.all()                                   # 카테고리부분 사이드바 내용 위해 추가해줌.
        context['no_category_item_count'] = Item.objects.filter(category=None).count
        context['manufacturers'] = Manufacturer.objects.all()

mall/templates/mall/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block head_title %}Shop{% endblock %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'mall/images/favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'mall/bootstrap4/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" media="screen">
        <script src="https://kit.fontawesome.com/eca5e2617c.js" crossorigin="anonymous"></script>
    </head>
    <body>
        {% include 'mall/navbar.html' %}

        <!-- Section-->
        <section class="py-5">
            <div class="container px-0 px-lg-0 mt-5">   <!--px-3 px-lg-4 mt-5-->
                <div class="container">
                    <div class="row">
                        <div class="col-md-8 col-lg-9" id="main-area">
                            {% block main_area %}
                            {% endblock %}

                        </div>
                        <div class="col-md-4 col-lg-3">
                             {% include 'mall/sidebar.html' %}
                        </div>
                    </div>
                </div>
            </div>
        </section>

        {% block Related_items_section %}
        {% endblock %}

        {% include 'mall/footer.html' %}

        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

    </body>
</html>

mall/templates/mall/comment_form.html
{% extends 'mall/base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
    Edit Comment - Item
{% endblock %}

{% block main_area %}
  <h1>Edit Comment</h1>
  <hr>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %} <!--csrf공격 막기 위함.-->

      {{form | crispy}}

    <button type="submit" class="btn btn-primary float-right">Submit</button>
  </form>

{% endblock %}

mall/templates/mall/footer.html
<!-- Footer-->
<footer class="py-5 bg-secondary">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-lg-6">
                <h2 class="text-white">Chocolate Museum</h2>
            </div>
            <div class="col-md-6 col-lg-6">
                <p class="text-white">회사 주소: 서울특별시 서대문구 신촌로 136길 34 1층 초콜릿 뮤지엄</p>
                <p class="text-white">고객센터 전화번호: 1544-3399</p>
                <p class="text-white">Copyright &copy; Chocolate Museum 2022</p>
            </div>
        </div>
    </div>
</footer>

mall/templates/mall/item_detail.html
{% extends 'mall/base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}
    {{item.name}} - Item
{% endblock %}

{% block main_area %}
                    <!-- Product section-->
                    <section class="py-5">
                        <div class="container px-4 px-lg-5 my-5">
                            <div class="row gx-4 gx-lg-5 align-items-center">
                                <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="{{item.image.url}}" alt="{{item}}의 image" /></div>
                                <div class="col-md-6">
                                    <div class="small mb-3">
                                        <!-- 수정 페이지로 이동 -->
                                        {% if item.category %}
                                            <div class="badge bg-light text-white position-absolute" style="top: 0rem; right: 3rem">
                                                <a href="{{item.category.get_absolute_url}}">{{item.category}}</a>
                                            </div>      <!--카테고리부분-->
                                        {% else %}
                                            <div class="badge bg-light text-white position-absolute" style="top: 0.5rem; right: 0.5rem">
                                                <a href="/mall/category/no_category/">미분류</a>
                                            </div>
                                        {% endif %}
                                        {% if item.tags.exists %}
                                        {% for t in item.tags.iterator %}
                                                <a class="badge badge-pill badge-light" href="{{t.get_absolute_url}}">{{t}}</a>
                                        {% endfor %}
                                        <br><br>
                                        {% endif %}
                                    </div>

                                    <h1 class="display-5 fw-bolder mb-10">{{item.name}}</h1>
                                    <div class="fs-5 mt-20">
                                        <span class="text-decoration-line-through">{{item.price}} ₩</span>
                                    </div>
                                    <a href="{{item.manufacturer.get_absolute_url}}">[{{item.manufacturer}}]</a>
                                    <p class="lead">{{item.get_description_markdown | safe}}</p>
                                    <p class="lead small">원산지: {{item.countryOfOrigin}}</p>

                                    {% if user.is_authenticated %}
                                    <div class="d-flex">
                                        <a class="btn btn-outline-dark flex-shrink-0" href="/mall/add_cart/{{item.pk}}">
                                            <i class="bi-cart-fill me-1"></i>
                                            Add to cart
                                        </a>
                                    </div>
                                        {% if user.is_superuser or user.is_staff %}
                                            <a href="/mall/update_item/{{item.pk}}/" role="button"
                                            class="btn btn-info btn-sm float-right">
                                            <i class ="fas fa-pen"> Edit Item</i>
                                         </a>
                                        {% endif %}
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </section>

<!-- Comments section-->
                    <div id="comment-area" class="mb-5">
                        <div class="card bg-light">
                            <div class="card-body">
                                <!-- Comment form-->
                                {% if user.is_authenticated %}
                                <form class="mb-4" id="comment-form" method="post"
                                    action="{{item.get_absolute_url}}new_comment/">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        {{comment_form | crispy}}
                                    </div>
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </form>
                                {% else %}
                                <a role="button" class="btn btn-dark btn-block btn-sm mb-2" href="#"
                                    data-toggle="modal" data-target="#loginModal">
                                    Log in and Leave a comment
                                </a>
                                {% endif %}
                                {% if item.comment_set.exists %}
                                {% for comment in item.comment_set.iterator %}
                                <!-- Single comment-->
                                <div class="media d-flex" id="comment-{{comment.pk}}">
                                    <img class="mr-3 rounded-circle" src="{{comment.get_avatar_url}}" alt="{{comment.author}}" width="60px" />
                                    <div class="media-body ms-3">
                                        {% if user.is_authenticated and comment.author == user %}
                                            <div class="float-right">
                                                <a role="button" class="btn btn-sm btn-info float-right"
                                                    href="/mall/update_comment/{{comment.pk}}/">
                                                    Edit
                                                </a>
                                                <a role="button" class="btn btn-sm btn-danger float-right"
                                                    data-toggle="modal" data-target="#deleteModal-{{comment.pk}}"
                                                    href="#">
                                                    Delete
                                                </a>
                                            </div>
                                            <!-- Modal -->
                                            <div class="modal fade" id="deleteModal-{{comment.pk}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                              <div class="modal-dialog">
                                                <div class="modal-content">
                                                  <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLabel">Are you sure?</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                      <span aria-hidden="true">&times;</span>
                                                    </button>
                                                  </div>
                                                  <div class="modal-body">
                                                      <del>{{comment | linebreaks}}</del>
                                                  </div>
                                                  <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                                    <a type="button" class="btn btn-secondary"
                                                        href="/mall/delete_comment/{{comment.pk}}/">
                                                        Delete
                                                    </a>
                                                  </div>
                                                </div>
                                              </div>
                                            </div>
                                        {% endif %}
                                        <div class="fw-bold">
                                            {{comment.author.username}}
                                            <small class="text-muted">{{comment.created_at}}</small>
                                        </div>
                                        <p>{{comment.content | linebreaks }}</p>
                                        {% if comment.created_at != comment.modified_at %}
                                            <p class="text-muted float-right">
                                                <small>Updated : {{comment.modified_at}}</small>
                                            </p>
                                        {% endif %}
                                    </div>
                                </div>
                                {% endfor %}
                                {% endif %}
                            </div>
                        </div>
                    </div>
{% endblock %}

mall/templates/mall/item_form.html
{% extends 'mall/base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
    Create Item - Shop
{% endblock %}

{% block main_area %}
  <h1>Create New Item</h1>
  <hr>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %} <!--csrf공격 막기 위함.-->

      {{form | crispy}}
      <div id="div_id_tags_str">
        <label for="id_tags">Tags:</label>
        <input type="text" id="id_tags" name="tags_str"
          class="textinput textInput form-control">
      </div>

    <button type="submit" class="btn btn-primary float-right mt-2">Submit</button>
  </form>
  {{form.media}}
{% endblock %}

mall/templates/mall/item_update_form.html
{% extends 'mall/base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
    Update Item - Shop
{% endblock %}

{% block main_area %}
  <h1>Update Item</h1>
  <hr>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %} <!--csrf공격 막기 위함.-->

      {{form | crispy}}
      <div id="div_id_tags_str">
        <label for="id_tags">Tags:</label>
        <input type="text" id="id_tags" name="tags_str" value="{{tags_str_default}}"
          class="textinput textInput form-control">
      </div>

      <br>

    <button type="submit" class="btn btn-primary float-right">Submit</button>
  </form>
  {{form.media}}
{% endblock %}